// apps/example-react/src/app/app.tsx
import { useState, useEffect } from 'react';
import { initClient, ApiFetcher } from 'tscont';
import { router, Post } from '@tscont/example-contracts';

const fetchApi: ApiFetcher = async ({ path, method, headers }) => {
  const result = await fetch(path, { method, headers }).then((res) =>
    res.json()
  );

  return { status: 200, data: result };
};

const client = initClient(router, {
  api: fetchApi,
  baseUrl: 'http://localhost:3333',
  baseHeaders: {},
});

export function App() {
  const [posts, setPosts] = useState<Post[] | null>(null);

  const fetchPosts = async () => {
    const { data } = await client.posts.getPosts();

    setPosts(data);
  };

  useEffect(() => {
    fetchPosts();
  }, []);

  return (
    <>
      <h1>Posts</h1>
      <ul>
        {posts?.map((post) => (
          <li>
            <h3 key={post.id}>
              {post.id} {post.title}
            </h3>
            <p>{post.body}</p>
          </li>
        ))}
      </ul>
    </>
  );
}

export default App;

// apps/example-microservice/web-app-vue/src/App.vue
<template>
  <div class="App">
    <h1>Posts from posts-service</h1>

    <div v-if="isLoading">Loading...</div>

    <div v-if="error">Error: {{ error }}</div>

    <div v-if="data">
      <div v-for="post in data.body" :key="post.id">
        <h2>{{ post.title }}</h2>
        <p>{{ post.content }}</p>
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
import { client } from './api/client';

const { data, error, isLoading } = client.getPosts.useQuery(['posts']);
</script>
